version: '3.6'
services:

  database:
    container_name: medium_database
    image: mongo
    ports:
      - "27017:27017"

  cache:
    container_name: medium_cache
    image: redis
    ports:
      - "6379:6379"
  
  backend_server_1:
    container_name: medium_backend_server_1
    image: node
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    ports:
      - "3001:3000"
    depends_on: 
      - database
      - cache
    environment: 
      - REDIS_HOST=redis://cache:6379
      - SWAGGER_PORT=3001
      - TZ=Asia/Singapore
    links:
      - cache:cache
      - database:database
    command: sh -c "npm install && npm run start"
  
  backend_server_2:
    container_name: medium_backend_server_2
    image: node
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    ports:
      - "3002:3000"
    depends_on:
      - database 
      - cache
    environment: 
      - REDIS_HOST=redis://cache:6379
      - SWAGGER_PORT=3001
      - TZ=Asia/Singapore
    links:
      - cache:cache
      - database:database
    command: sh -c "npm install && npm run start"

  ui_server:
    container_name: medium_ui_server
    image: node
    working_dir: /home/node/app
    ports: 
      - "3003:3000"
    volumes:
      - ./client:/home/node/app
    depends_on: 
      - backend_server_1
      - backend_server_2
    command: sh -c "npm install && npm run start"
  
  proxy_server:
    container_name: medium_proxy_server
    image: nginx
    volumes:
      - ./settings/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on: 
      - backend_server_1
      - backend_server_2
      - ui_server
    links:
      - backend_server_1:backend_server_1
      - backend_server_2:backend_server_2
      - ui_server:ui_server
    command: [nginx-debug, '-g', 'daemon off;']